[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "freetype",
  "harfbuzz",
  "liberation_ttf",
  "glib",
  "dbus",
  "at-spi2-atk",
  "cups",
  "libdrm",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "expat",
  "fontconfig",
  "mesa"
]